name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test with coverage
        run: >
          dotnet test --configuration Release --no-build
          /p:CollectCoverage=true
          /p:CoverletOutput=TestResults/coverage/
          /p:CoverletOutputFormat=cobertura

      - name: Publish coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: "**/TestResults/coverage/*.cobertura.xml"
